theme: jekyll-theme-minimal
title: [Guanyi Chen]
description: [I am a PhD student in CLAN\, University of Aberdeen\, working on Natural Language Generation. I am supervised by Prof. Kees van Deemter and Dr. Chenghua Lin.]