theme: jekyll-theme-minimal
title: [Guanyi Chen]
description: [I am a PhD student in CLAN&#44; University of Aberdeen&#44; work on Natural Language Generation. I am supervised by Prof. Kees van Deemter and Dr. Chenghua Lin.]